### ISSUE TITLE
SaveSlot.extractFromFile() fails if slots 1 or 2 are unused

### ISSUE THREAD

**Issue by kris-joseph** [probabilist/legends#1]
The decrypt function iterates through the range of 0-2, but if there are no data files for save slots 1 or 2, the dictionary keys don't exist when referenced by the function. Workaround is to create basic game saves in those slots... but a test to see if the key exists would probably fix it

**Comment by probabilist** [comment]
https://github.com/probabilist/legends/blob/5a8b03a48616584c93d61f6479a2942e77a30f2d/legends/classes/saveslot.py#L187

There's no iteration. You can either specify the slot, or it will use the default, which is 0. I don't have a game save in slot 2, and it works for me.
