### ISSUE TITLE
Unable to use incompleteMissions

### ISSUE THREAD

**Issue by kip-d** [probabilist/legends#4]
\>>> from legends import *
\>>> mySave = SaveSlot()
\>>> mySave.extractFromFile()
\>>> mySave.incompleteMissions
 Traceback (most recent call last):
   File "\<stdin>", line 1, in <module>
   File "/Users/kip/src/StarTrek/legends/classes/saveslot.py", line 123, in incompleteMissions
     percent = data[dataDiff]['complete_pct'] 
 KeyError: 'Doom'

Expected to see a list of incomplete missions.  I have not finished all of the Expert level missions.  I have finished all the normal and advanced ones.

**Comment by probabilist** [comment]
This should be fixed now. Please try it again.
